import pandas as pd

# raw data (from web scraping) csv column headings
return_df = pd.DataFrame(columns=['idx', 'country', 'region', 'city', 'store', 'name', 'brand', 'aisle',
                                  'subaisle', 'subsubaisle', 'size', 'price', 'multi_price', 'old_price', 'pricePerUnit',
                                  'itemNum', 'description', 'serving', 'img_urls', 'item_label',
                                  'item_ingredients', 'deliveryCo', 'url', 'timeStamp'])

# cleaned data csv column headings
clean_dat = pd.DataFrame(columns=["ID",
                                  "Country",
                                  "Store_CHI",
                                  "DeliveryCo_CHI",
                                  "Region_CHI",
                                  "City_CHI",
                                  "ProductAisle",
                                  "ProductAisle_DV",
                                  "ProductCategory",
                                  "ProductSubCategory",
                                  "ProductSubCategory_DV",
                                  "ProductImages",
                                  "ProductBrand",
                                  "ProductName",
                                  "ProductVariety",
                                  "ProductFlavour",
                                  "Packsize_org",
                                  "Unitpp",
                                  "Containersize_org",
                                  "Containersize_val",
                                  "Containersize_unit",
                                  "Pack_type",
                                  "Netcontent_org",
                                  "Netcontent_val",
                                  "Netcontent_unit",
                                  "Description",
                                  "Ingredients",
                                  "NutrInfo_org",
                                  "Serving_org",
                                  "Servsize_container_type_org",
                                  "Servsize_container_type_val",
                                  "Servsize_container_type_unit",
                                  "Servsize_portion_org",
                                  "Servsize_portion_val",
                                  "Servsize_portion_unit",
                                  "Servings_cont",
                                  "Nutr_label",
                                  "Cals_org_pp",
                                  "Cals_value_pp",
                                  "Cals_unit_pp",
                                  "TotalCarb_g_pp",
                                  "TotalCarb_pct_pp",
                                  "TotalSugars_g_pp",
                                  "TotalSugars_pct_pp",
                                  "AddedSugars_g_pp",
                                  "AddedSugars_pct_pp",
                                  "Cals_value_p100g",
                                  "Cals_unit_p100g",
                                  "TotalCarb_g_p100g",
                                  "TotalCarb_pct_p100g",
                                  "TotalSugars_g_p100g",
                                  "TotalSugars_pct_p100g",
                                  "AddedSugars_g_p100g",
                                  "AddedSugars_pct_p100g",
                                  "ProdType",
                                  "StorType",
                                  "ItemNum",
                                  "SKU",
                                  "UPC",
                                  "URL",
                                  "DataCaptureTimeStamp",
                                  "Notes",])
